name: nyanya_rocket_base
description: NyaNya Rocket! base package.
author: CaramelDunes
homepage: https://github.com/CaramelDunes/nyanya_rocket_base

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  protobuf: ^2.0.0
  fixnum: ^1.0.0

dev_dependencies:
  test: ^1.16.2