name: nyanya_rocket_base
description: NyaNya Rocket! base package.
author: CaramelDunes
homepage: https://github.com/CaramelDunes/nyanya_rocket_base

version: 0.0.1-nullsafety.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  protobuf: ^2.0.0-nullsafety.0
  fixnum: ^1.0.0-nullsafety.0

dev_dependencies:
  test: ^1.16.0-nullsafety.12