name: nyanya_rocket_base
description: NyaNya Rocket! base package.
author: CaramelDunes
homepage: https://github.com/CaramelDunes/nyanya_rocket_base

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  protobuf: ^1.0.1
  fixnum: ^0.10.11

dev_dependencies:
  test: ^1.5.3